---
- name: Deploy App
  hosts: app
  become: true

  tasks:

  - name: Git Install
    apt:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
    notify: reload puma
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit

  handlers:

  - name: reload puma
    systemd: name=puma state=restarted
